k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 5000
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: amd64-deptno@amd64
  currentCluster: amd64
  clusters:
    amd64:
      namespace:
        active: devpod
        lockFavorites: true
        favorites:
        - all
        - postgresql
        - deptno
        - ai
        - tubemon-dev
        - tubemon
        - stock-dev
        - stock
        - devpod
        - home-assistant
      view:
        active: po
      featureGates:
        nodeShell: true
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/yr/lb2jlrrd1fs7h6hn30n_ksvr0000gn/T/k9s-screens-deptno
